### ISSUE TITLE
Prefix property is undefined

### ISSUE THREAD

**Issue by footniko** [kop/node-twelve-factor-config#2]
In case you don't need to use the `Prefix` when creating an instance, you'll encounter `Cannot read property 'prefix' of undefined` error.
Instead of
```
  constructor(settings) {
    this.prefix = settings.prefix || '';
  }
```
i believe it's better to use:
```
  constructor(settings = {}) {
    this.prefix = settings.prefix || '';
  }
```

**Comment by kop** [comment]
@footniko,
Good job noticing this. Please feel free to submit a PR.
Thanks!
